apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-app
  namespace: default
spec:
  values:
    clusterName: "newyork"
    image:
      tag: "1.0.0"
    gateway:
      enabled: true
      hostname: "newyork.demo.qws.xyz"
      mcsHostname: "newyork-mcs.demo.qws.xyz"
      headlessHostname: "newyork-headless.demo.qws.xyz"
