apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - release.yaml

configMapGenerator:
  - name: cilium-values
    namespace: flux-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
