kubeProxyReplacement: true
k8sServicePort: 6443

ingressController:
  enabled: true
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443
  gatewayAPI:
    gatewayClassName: cilium

socketLB:
  hostNamespaceOnly: true

l2announcements:
  enabled: false

prometheus:
  # FIXME: Enable if you are using prometheus / prometheus operator
  enabled: false
  serviceMonitor:
    enabled: false

gatewayAPI:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
