apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demo-app
  namespace: default
spec:
  values:
    clusterName: "paris"
    image:
      tag: "1.0.0"
    gateway:
      enabled: true
      hostname: "paris.demo.qws.xyz"
      mcsHostname: "paris-mcs.demo.qws.xyz"
      headlessHostname: "paris-headless.demo.qws.xyz"
