---
ansible_user: quentin
ansible_scp_if_ssh: true
ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null

k8s_version: "1.34"
k8s_version_full: "1.34.3"
service_cidr: "10.96.0.0/12"
