---
installCRDs: true

cluster:
  name: cluster-paris
  id: 1

ipam:
  operator:
    clusterPoolIPv4PodCIDRList:
      - 10.200.0.0/16

kubeProxyReplacement: true
k8sServiceHost: cp.paris.internal
k8sServicePort: 6443
envoy:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    auto:
      method: cronJob
