apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loadbalancer-pool.yaml
patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: cilium-gateway-cilium-gateway
      namespace: kube-system
